"""empty message

Revision ID: 23f18147375
Revises: 577cfe172bd3
Create Date: 2014-02-25 00:08:40.810076

"""

# revision identifiers, used by Alembic.
revision = '23f18147375'
down_revision = '577cfe172bd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
