"""empty message

Revision ID: 36ab9817eeb1
Revises: 2f11b666b6da
Create Date: 2014-02-13 21:39:11.195600

"""

# revision identifiers, used by Alembic.
revision = '36ab9817eeb1'
down_revision = '2f11b666b6da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(length=30), nullable=True))
    op.drop_column('users', u'first_name')
    op.drop_column('users', u'last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'last_name', sa.VARCHAR(length=30), nullable=True))
    op.add_column('users', sa.Column(u'first_name', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    ### end Alembic commands ###
