"""empty message

Revision ID: 5319a27cf316
Revises: 36ab9817eeb1
Create Date: 2014-02-13 23:03:35.044846

"""

# revision identifiers, used by Alembic.
revision = '5319a27cf316'
down_revision = '36ab9817eeb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
