"""empty message

Revision ID: 577cfe172bd3
Revises: 2f11b666b6da
Create Date: 2014-02-23 02:28:29.962058

"""

# revision identifiers, used by Alembic.
revision = '577cfe172bd3'
down_revision = '2f11b666b6da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('placeholder', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userattributes')
    op.drop_table('attributes')
    ### end Alembic commands ###
